package com.cloudsoftcorp.monterey.example.noapisimple.impl;

import java.io.Serializable;

/**
 * Generated by Cloudsoft Monterey.
 */
public class HelloeeImpl implements com.cloudsoftcorp.monterey.example.noapisimple.Helloee, Serializable {
    private static final long serialVersionUID = 8750002490670537758L;

    @Override
    public String hello(String msg) {
        return "hello, "+msg;
    }
}
