package brooklyn.event.basic;

import groovy.transform.InheritConstructors

import brooklyn.entity.Entity
import brooklyn.event.SensorEvent
import brooklyn.event.Sensor

/**
 * A {@link SensorEvent} containing data from a {@link Sensor} generated by an {@link Entity}.
 */
public class BasicSensorEvent<T> implements SensorEvent<T> {
    private final Sensor<T> sensor;
    private final Entity source;
    private final T value;
    private final long timestamp;
    
    public T getValue() { return value; }

    public Sensor<T> getSensor() { return sensor; }

    public Entity getSource() { return source; }

    public long getTimestamp() { return timestamp; }

    public BasicSensorEvent(Sensor<T> sensor, Entity source, T value, long timestamp=0) {
        this.sensor = sensor;
        this.source = source;
        this.value = value;

        if (timestamp > 0) {
            this.timestamp = timestamp;
        } else {
            this.timestamp = System.currentTimeMillis();
        }
    }
    
    public String toString() {
        return "${source}.$sensor=$value @ $timestamp"
    }
}
