package com.cloudsoftcorp.monterey.example.noapisimple;

import com.cloudsoftcorp.monterey.servicebean.access.api.MontereyNetworkEndpoint;

/**
 * Generated by Cloudsoft Monterey.
 */
public class HelloCloudServiceLocatorImpl implements com.cloudsoftcorp.monterey.example.noapisimple.HelloCloudServiceLocator {

    private final MontereyNetworkEndpoint networkEndpoint;
    private final Class<com.cloudsoftcorp.monterey.example.noapisimple.Helloee> clazz = com.cloudsoftcorp.monterey.example.noapisimple.Helloee.class;
    private long serviceCallsTimeoutInMillis = 20 * 1000L;
    
    public HelloCloudServiceLocatorImpl(MontereyNetworkEndpoint networkEndpoint) {
        if (networkEndpoint == null) {
            throw new NullPointerException("Network-endpoint must not be null");
        }
        this.networkEndpoint = networkEndpoint;
    }
    
    public void setServiceCallsTimeoutInMillis(long serviceCallsTimeoutInMillis) {
        this.serviceCallsTimeoutInMillis = serviceCallsTimeoutInMillis;
    }
    
    public com.cloudsoftcorp.monterey.example.noapisimple.Helloee getService(String name) {
        return networkEndpoint.getService(clazz, name, serviceCallsTimeoutInMillis);
    }
}
